## Purpose: When sync-versions modifies Dependabot PR branches, Dependabot stops
## auto-rebasing. After merges to main, this nudges conflicted PRs to be
## recreated by commenting "@dependabot recreate".
name: Nudge Dependabot to recreate on conflicts

on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  dependabot-recreate:
    runs-on: ubuntu-latest
    steps:
      - name: Comment @dependabot recreate on conflicted PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPENDABOT_PAT }}
          script: |
            try {
              const { data: me } = await github.rest.users.getAuthenticated();
              console.log(`Authenticated as: ${me.login}`);
            } catch (e) {
              console.log('Could not determine authenticated user:', e.message || e);
            }

            const sleep = (ms) => new Promise(r => setTimeout(r, ms));

            // wait for mergeable_state to be computed, polling every 60 seconds up to 10 minutes
            async function waitForMergeableState(owner, repo, number, maxMs = 600000, delay = 60000) {
              let waitedMs = 0;
              let state = 'unknown';
              while (waitedMs < maxMs) {
                const { data } = await github.rest.pulls.get({ owner, repo, pull_number: number });
                state = data.mergeable_state || 'unknown';
                console.log(`PR #${number}: mergeable_state=${state} (waited ${waitedMs}ms)`);
                if (state !== 'unknown') return state;
                await sleep(delay);
                waitedMs += delay;
              }
              return state;
            }

            console.log('Listing open PRs to base=main...');
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
              per_page: 100
            });

            console.log(`Found ${prs.length} open PR(s) to main.`);
            const dependabotPRs = prs.filter(pr => pr.user && pr.user.login === 'dependabot[bot]');
            console.log(`Filtered to ${dependabotPRs.length} Dependabot PR(s).`);

            for (const pr of dependabotPRs) {
              console.log(`\nInspecting PR #${pr.number}: ${pr.title}`);
              const state = await waitForMergeableState(context.repo.owner, context.repo.repo, pr.number);
              console.log(`Final mergeable_state for #${pr.number}: ${state}`);
              // Don't try to recreate PRs that already can be merged.
              if (state !== 'dirty') {
                console.log(`Skipping PR #${pr.number}: not in conflict (mergeable_state != 'dirty').`);
                continue;
              }

              try {
                const { data: comment } = await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: '@dependabot recreate'
                });
                console.log(`Commented on PR #${pr.number} successfully. comment_id=${comment.id}${comment.html_url ? ` url=${comment.html_url}` : ''}`);
              } catch (error) {
                const status = error.status || (error.response && error.response.status);
                const msg = (error.response && error.response.data && error.response.data.message) || error.message || String(error);
                console.log(`Failed to comment on PR #${pr.number}. status=${status} message=${msg}`);
              }
            }
