name: Monthly Pre-commit Hook Updates

on:
  schedule:
    # Run on the 1st of every month at 2 AM UTC
    - cron: "0 2 1 * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-precommit:
    name: "Update Pre-commit Hooks"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Poe
        run: |
          pipx install poethepoet

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Update pre-commit hooks in example-package
        working-directory: example-package
        run: |
          poetry install --no-interaction
          poetry run poe hooks-update

      - name: Run pre-commit sync script
        run: |
          poe sync-precommit

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Files changed:"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          body: |
            This PR was automatically created by the monthly pre-commit hook update workflow.

            Changes include:
            - Updated pre-commit hooks in `example-package/`
            - Synced updated hook versions to template files

            The workflow runs monthly to ensure all pre-commit hooks stay up-to-date.
          branch: "chore/update-precommit-hooks"
          delete-branch: true
